# Generated by Django 2.0.2 on 2018-02-19 01:03

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kingdom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_link', models.CharField(max_length=100)),
                ('full_link', models.CharField(max_length=100)),
                ('indices', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='kingdom',
            name='map_im_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MapDisplayer.Map'),
        ),
    ]
