# Generated by Django 2.0.2 on 2018-03-12 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MapDisplayer', '0003_auto_20180312_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='parentMap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MapDisplayer.Map'),
        ),
    ]
