# Generated by Django 2.0.2 on 2018-04-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapDisplayer', '0004_auto_20180312_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='isPrivate',
            field=models.BooleanField(default=False),
        ),
    ]
