# Generated by Django 2.0.2 on 2018-04-05 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapDisplayer', '0007_auto_20180405_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='Accesible_Maps', to=settings.AUTH_USER_MODEL),
        ),
    ]
